### ISSUE TITLE
dimmerbox - unavailable

### ISSUE THREAD

**Issue by trommegutten** [d4m/hassio_components#1]
Hello,
I think I have set up everything correctly in Home Assistant.
1. The script is in: config/custom_components/light/blebox_dimmerbox.py
2. I've included this in configuration.yaml 
```
light:
  - platform: blebox_dimmerbox
    host: 192.168.2.168
```
3. Restart HA
4. HA finds dimmerbox, and it shows up in the lights panel, but it is marked as "unavailable" and I am not able to do any controlling.

Do you know what's wrong? Can you point me in the right direction?

![blebox_unavailable1](https://user-images.githubusercontent.com/12217243/46581370-a381b980-ca37-11e8-9a94-397ac0577b99.jpeg)

![blebox_unavailable2](https://user-images.githubusercontent.com/12217243/46581371-a8df0400-ca37-11e8-94a2-68a81d312ff1.jpeg)

**Comment by rothvaw** [comment]
Hi!
I made changes to dimmerBox component to be consistent with API level 20170829.
It is in PR: https://github.com/d4m/hass_blebox/pull/2

**Comment by trommegutten** [comment]
Thanks!😃 I can confirm it’s working now. It’s a great plugin👍🏻
