### ISSUE TITLE
SwitchBox przestał działać

### ISSUE THREAD

**Issue by kuba-str** [d4m/hassio_components#3]
Po aktualizacji API do 20180604, przestał działać dodatek. Pokazuje się że jest niedostępny.

{"device":{"deviceName":"Obraz","type":"switchBox","fv":"0.927","hv":"0.6","universe":0,"apiLevel":"20180604","id":"5ecf7fb0be75","ip":"192.168.5.212","availableFv":null}}

**Comment by d4m** [comment]
Poprawione, kod dostosowany do zmian w API switchBoxa.
