### ISSUE TITLE
HA 105.3 - issue after upgrade

### ISSUE THREAD

**Issue by wochen** [d4m/hassio_components#6]
HA: 105.3
Device: Switchbox

`2020-02-12 21:02:40 ERROR (MainThread) [custom_components.blebox_switchbox.switch] blebox_switchbox (192.168.1.100): Cannot determine the device type`

This message is now showing in logs - after upgrading to 105.3.
The device is unavailable.

Thanks in advance for helping with this.

**Comment by d4m** [comment]
I've tested component on version 0.105.3 and for me all works fine.
Try add device type to your configuration.ini, e.g:

switch:
  - platform: blebox_switchbox
    host: 192.168.1.100
    type: switchBox

**Comment by wochen** [comment]
Hi @d4m,

thanks for your reply.
It looks like, after adding a type, it works just fine now.

Many thanks.
